### ISSUE TITLE
gpuCI for Dask org members

### ISSUE THREAD

**Issue by quasiben** [rapidsai/dask-build-environment#2]
I _think_ gpuCI should be running for anyone in the dask org.  In this [PR the GPUTester bot pops op](https://github.com/dask/distributed/pull/5112#issuecomment-890263489) even though  `gjoseph92` is in the dask org

**Comment by raydouglass** [comment]
This was discussed offline. `gjoseph92` doesn't have public membership. `gjoseph92` was added to the allow list manually.

**Comment by jrbourbeau** [comment]
Thanks @raydouglass!
