### ISSUE TITLE
Updating Python versions

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/dask-build-environment#93]
As RAPIDS already supports Python 3.11 ( https://github.com/rapidsai/build-planning/issues/3 ), it would be good to test Dask with it as well

Also RAPIDS is planning to add Python 3.12 ( https://github.com/rapidsai/build-planning/issues/40 ), which would be good to start testing for

An open question is when we drop Python 3.9. Both NEP 29 and SPEC 0 recommend dropping it, so maybe that is reasonable to do? This may depend on when RAPIDS and Dask decide to drop it as well

**Comment by charlesbluca** [comment]
> As RAPIDS already supports Python 3.11 ( https://github.com/rapidsai/build-planning/issues/3 ), it would be good to test Dask with it as well

Yeah it looks like we're publishing 3.11 Dask GPU CI images as of https://github.com/rapidsai/dask-build-environment/pull/91, think all that's needed beyond that is actually adding these builds to the matrix in each of the tested Dask repos - can do that now and check if any failures crop up

> Both NEP 29 and SPEC 0 recommend dropping it, so maybe that is reasonable to do?

Yeah I'm in favor of the proposal in https://github.com/rapidsai/build-planning/issues/40 to drop 3.9 testing support around the same time that 3.12 is added

**Comment by charlesbluca** [comment]
Looks like we already had Distributed's GPU CI running against 3.11 with https://github.com/dask/distributed/pull/8598, opened PRs to do the same for the other Dask repos:

- https://github.com/dask/dask/pull/11135
- https://github.com/dask/dask-image/pull/376
- https://github.com/dask-contrib/dask-sql/pull/1335

**Comment by charlesbluca** [comment]
Looks like 3.11 testing is rolled out everywhere 🎉 @jakirkham is this good to close or would you like to keep this open to track the 3.12 work as it becomes available?

**Comment by jakirkham** [comment]
Yeah let's close. We can open a new one for Python 3.12 when relevant

**Comment by jakirkham** [comment]
Thanks Charles! 🙏
